name: Update Reading Stats
# on:
#   push:
#     paths: ['goodreads_library_export.csv']
on:
  push:
    branches: [main]

permissions:
  contents: write  # Grant write access to repository contents    

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install pandas requests beautifulsoup4

      - name: Run Python script for data generation
        run: python process_goodreads.py
        env:
          GOOGLE_BOOKS_API_KEY: ${{ secrets.GOOGLE_BOOKS_API_KEY }}

      - name: Commit and push changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add reading_stats.json
          git commit -m "Update reading stats" || echo "No changes"
          git push          