name: Update Reading Stats
on:
  push:
    paths: ['goodreads_library_export.csv']
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: '3.x' }
      - run: pip install pandas
      - run: python process_goodreads.py
      - run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add reading_stats.json
          git commit -m "Update reading stats" || echo "No changes"
          git push